package com.jerotes.jvpillage.init;

import com.jerotes.jvpillage.JVPillage;
import net.minecraft.ChatFormatting;
import net.minecraft.core.registries.Registries;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.ListTag;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.entity.BannerPattern;
import net.minecraft.world.level.block.entity.BannerPatterns;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.RegistryObject;

public class JVPillageTabs {
	public static final DeferredRegister<CreativeModeTab> REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, JVPillage.MODID);
	//方块-物品-工具-盔甲-刷怪蛋
	public static final RegistryObject<CreativeModeTab> JEROTESVILLAGE_TAB = REGISTRY.register("jerotesvillage_tab",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.jvpillage.jerotesvillage_tab")).icon(() -> new ItemStack(JVPillageItems.JEROTESVILLAGE.get())).displayItems((parameters, tabData) -> {

						tabData.accept(CarvedBanner());

						//冒险
						tabData.accept(JVPillageItems.SECOND_ROUND_ANCHOR_CORE.get());
						//沉降
						tabData.accept(JVPillageItems.SEDIMENT_MUD_BRICKS.get());
						tabData.accept(JVPillageItems.SEDIMENT_MUD_BRICK_STAIRS.get());
						tabData.accept(JVPillageItems.SEDIMENT_MUD_BRICK_SLAB.get());
						tabData.accept(JVPillageItems.SEDIMENT_MUD_BRICK_WALL.get());
						tabData.accept(JVPillageItems.SEDIMENT_MOISTURE_PROOF_PASTE.get());
						tabData.accept(JVPillageItems.SEDIMENT_COFFIN.get());
						tabData.accept(JVPillageItems.SEDIMENT_URN.get());
						//灾厄
						tabData.accept(JVPillageItems.ILLAGER_SIGNAL_LIGHT.get());
						tabData.accept(JVPillageItems.GLOW_SHINE.get());
						tabData.accept(JVPillageItems.OMINOUS_TORCH.get());
						tabData.accept(JVPillageItems.EXPLORER_TRACKED_ROCORD.get());
						tabData.accept(JVPillageItems.SECOND_ROUNDER_MAP.get());
						tabData.accept(JVPillageItems.ILLAGER_TOWER_MAP.get());
						tabData.accept(JVPillageItems.GUIDELINES_FOR_THE_CRAFT_OF_THE_SECONDER_ROUND_GEM.get());
						tabData.accept(JVPillageItems.SECOND_ROUNDER_GEM.get());
						tabData.accept(JVPillageItems.SECOND_ROUND_WORLD_TELEPORT_STONE.get());
						tabData.accept(JVPillageItems.OMINOUS_BANNER_RAID_TAG_DEPLOYER.get());
						tabData.accept(JVPillageItems.GLORY_BANNER_RAID_TAG_DEPLOYER.get());
						tabData.accept(JVPillageItems.EXPLORER_CAMP_MAP.get());
						tabData.accept(JVPillageItems.EXECUTIONERS_AXE.get());
						tabData.accept(JVPillageItems.EXECUTIONERS_HAMMER.get());
						tabData.accept(JVPillageItems.EXECUTIONERS_HALBERD.get());
						tabData.accept(JVPillageItems.OMINOUS_BOMB.get());
						tabData.accept(JVPillageItems.OMINOUS_CUTLASS.get());
						tabData.accept(JVPillageItems.OMINOUS_DAGGER.get());
						tabData.accept(JVPillageItems.OMINOUS_MACE.get());
						tabData.accept(JVPillageItems.OMINOUS_BOW.get());
						tabData.accept(JVPillageItems.OMINOUS_JAVELIN.get());
						tabData.accept(JVPillageItems.BITTER_COLD_SORCERY_GLOVE.get());
						tabData.accept(JVPillageItems.GRAVITY_COPPER_BALL.get());
						tabData.accept(JVPillageItems.SLAVERY_SUPERVISOR_HAMMER_WHIP.get());
						tabData.accept(JVPillageItems.FIREPOWER_POURER_CHAINSAW.get());
						tabData.accept(JVPillageItems.FIREPOWER_POURER_CROSSBOW.get());
						tabData.accept(JVPillageItems.CRAZY_AXE.get());
						tabData.accept(JVPillageItems.OMINOUS_WAR_BEAST_ARMOR.get());
						tabData.accept(JVPillageItems.OMINOUS_GIANT_BEAST_ARMOR.get());
						tabData.accept(JVPillageItems.EXPLORER_IRON_UPGRADE_SMITHING_TEMPLATE.get());
						tabData.accept(JVPillageItems.EXPLORER_IRON_HELMET.get());
						tabData.accept(JVPillageItems.EXPLORER_IRON_CHESTPLATE.get());
						tabData.accept(JVPillageItems.EXPLORER_IRON_LEGGINGS.get());
						tabData.accept(JVPillageItems.EXPLORER_IRON_BOOTS.get());
						tabData.accept(JVPillageItems.EXPLORER_UPGRADE_SMITHING_TEMPLATE.get());
						tabData.accept(JVPillageItems.EXPLORER_HELMET.get());
						tabData.accept(JVPillageItems.EXPLORER_CHESTPLATE.get());
						tabData.accept(JVPillageItems.EXPLORER_LEGGINGS.get());
						tabData.accept(JVPillageItems.EXPLORER_BOOTS.get());
						tabData.accept(JVPillageItems.HORNED_HELMET.get());
						tabData.accept(JVPillageItems.WARLOCK_TIARA.get());
						tabData.accept(JVPillageItems.SLAVERY_SUPERVISOR_UPGRADE_SMITHING_TEMPLATE.get());
						tabData.accept(JVPillageItems.SLAVERY_SUPERVISOR_HELMET.get());
						tabData.accept(JVPillageItems.SLAVERY_SUPERVISOR_CHESTPLATE.get());
						tabData.accept(JVPillageItems.SLAVERY_SUPERVISOR_LEGGINGS.get());
						tabData.accept(JVPillageItems.SLAVERY_SUPERVISOR_BOOTS.get());
						tabData.accept(JVPillageItems.OMINOUS_PROBE.get());
						tabData.accept(JVPillageItems.OMINOUS_BANNER_PROJECTION_EMERALD_FRAGMENT.get());
						tabData.accept(JVPillageItems.MUSIC_DISC_OMINOUS_BANNER_PROJECTION.get());
						tabData.accept(JVPillageItems.BOUND_ZOMBIE_VILLAGER_SPAWN_EGG.get());
						tabData.accept(JVPillageItems.EXPLORER_SPAWN_EGG.get());
						tabData.accept(JVPillageItems.EXECUTIONER_SPAWN_EGG.get());
						tabData.accept(JVPillageItems.MAPMAKER_SPAWN_EGG.get());
						tabData.accept(JVPillageItems.DEFECTOR_SPAWN_EGG.get());
						tabData.accept(JVPillageItems.BANNER_BEARER_SPAWN_EGG.get());
						tabData.accept(JVPillageItems.BLASTER_SPAWN_EGG.get());
						tabData.accept(JVPillageItems.TRUMPETER_SPAWN_EGG.get());
						tabData.accept(JVPillageItems.TELEPORTER_SPAWN_EGG.get());
						tabData.accept(JVPillageItems.CYCLONER_SPAWN_EGG.get());
						tabData.accept(JVPillageItems.JAVELIN_THROWER_SPAWN_EGG.get());
						tabData.accept(JVPillageItems.ZOMBIE_KEEPER_SPAWN_EGG.get());
						tabData.accept(JVPillageItems.BITTER_COLD_SORCERER_SPAWN_EGG.get());
						tabData.accept(JVPillageItems.PURPLE_SAND_WITCH_SPAWN_EGG.get());
						tabData.accept(JVPillageItems.FIRE_SPITTER_SPAWN_EGG.get());
						tabData.accept(JVPillageItems.WILD_FINDER_SPAWN_EGG.get());
						tabData.accept(JVPillageItems.SUBMARINER_SPAWN_EGG.get());
						tabData.accept(JVPillageItems.LAMP_WIZARD_SPAWN_EGG.get());
						tabData.accept(JVPillageItems.SLAVERY_SUPERVISOR_SPAWN_EGG.get());
						tabData.accept(JVPillageItems.FIREPOWER_POURER_SPAWN_EGG.get());
						tabData.accept(JVPillageItems.NECROMANCY_WARLOCK_SPAWN_EGG.get());
						tabData.accept(JVPillageItems.GAVILER_SPAWN_EGG.get());
						tabData.accept(JVPillageItems.AX_CRAZY_SPAWN_EGG.get());
						tabData.accept(JVPillageItems.OMINOUS_BANNER_PROJECTION_SPAWN_EGG.get());
						//苦寒
						tabData.accept(JVPillageItems.SNOW_FROZEN_SOIL.get());
						tabData.accept(JVPillageItems.ICE_ROCK.get());
						tabData.accept(JVPillageItems.GIANT_MONSTER_HAIR.get());
						tabData.accept(JVPillageItems.GIANT_MONSTER_HORN.get());
						tabData.accept(JVPillageItems.GIANT_MONSTER_HELMET.get());
						tabData.accept(JVPillageItems.GIANT_MONSTER_HORNED_HELMET.get());
						tabData.accept(JVPillageItems.GIANT_MONSTER_CHESTPLATE.get());
						tabData.accept(JVPillageItems.GIANT_MONSTER_LEGGINGS.get());
						tabData.accept(JVPillageItems.GIANT_MONSTER_BOOTS.get());
						tabData.accept(JVPillageItems.ICE_ROCK_THROWING_BALL.get());
						tabData.accept(JVPillageItems.WILDERNESS_WOLF_SPAWN_EGG.get());
						tabData.accept(JVPillageItems.GIANT_MONSTER_SPAWN_EGG.get());
						//紫沙
						tabData.accept(JVPillageItems.PURPLE_SAND.get());
						tabData.accept(JVPillageItems.PURPLE_SANDSTONE.get());
						tabData.accept(JVPillageItems.PURPLE_SANDSTONE_STAIRS.get());
						tabData.accept(JVPillageItems.PURPLE_SANDSTONE_SLAB.get());
						tabData.accept(JVPillageItems.PURPLE_SANDSTONE_WALL.get());
						tabData.accept(JVPillageItems.CHISELED_PURPLE_SANDSTONE.get());
						tabData.accept(JVPillageItems.SMOOTH_PURPLE_SANDSTONE.get());
						tabData.accept(JVPillageItems.SMOOTH_PURPLE_SANDSTONE_STAIRS.get());
						tabData.accept(JVPillageItems.SMOOTH_PURPLE_SANDSTONE_SLAB.get());
						tabData.accept(JVPillageItems.CUT_PURPLE_SANDSTONE.get());
						tabData.accept(JVPillageItems.CUT_PURPLE_SANDSTONE_SLAB.get());
						tabData.accept(JVPillageItems.ENCHANTED_STONE.get());
						tabData.accept(JVPillageItems.SPIRVE_HEAD.get());
						tabData.accept(JVPillageItems.HAGS_CAULDRON.get());
						tabData.accept(JVPillageItems.UNSTABLE_HAGS_CAULDRON.get());
						tabData.accept(JVPillageItems.DIRTY_HAGS_CAULDRON.get());
						tabData.accept(JVPillageItems.NEW_HAGS_CAULDRON.get());
						tabData.accept(JVPillageItems.PURPLE_SANDWICH.get());
						tabData.accept(JVPillageItems.WITCH_COVEN_MAP.get());
						tabData.accept(JVPillageItems.WITCH_RESIDENCE_MAP.get());
						tabData.accept(JVPillageItems.SPIRVE_HELMET.get());
						tabData.accept(JVPillageItems.SPIRVE_CHESTPLATE.get());
						tabData.accept(JVPillageItems.SPIRVE_LEGGINGS.get());
						tabData.accept(JVPillageItems.SPIRVE_BOOTS.get());
						tabData.accept(JVPillageItems.SPIRVE_BROOM.get());
						tabData.accept(JVPillageItems.SPIRVE_DUSTPAN.get());
						tabData.accept(JVPillageItems.SPIRVE_INSECT_NET.get());
						tabData.accept(JVPillageItems.SPIRVE_MOP.get());
						tabData.accept(JVPillageItems.SPIRVE_KITCHEN_KNIFE.get());
						tabData.accept(JVPillageItems.SPIRVE_SPATULA.get());
						tabData.accept(JVPillageItems.SPIRVE_PAN.get());
						tabData.accept(JVPillageItems.SPIRVE_GOURD_LADLE.get());
						tabData.accept(JVPillageItems.SPIRVE_SAW.get());
						tabData.accept(JVPillageItems.SPIRVE_FRAME_SAW.get());
						tabData.accept(JVPillageItems.SPIRVE_PINCER.get());
						tabData.accept(JVPillageItems.SPIRVE_SISSORS.get());
						tabData.accept(JVPillageItems.SPIRVE_RAZOR.get());
						tabData.accept(JVPillageItems.SPIRVE_DUSTER.get());
						tabData.accept(JVPillageItems.SPIRVE_BROKEN_BOOTLE.get());
						tabData.accept(JVPillageItems.SPIRVE_FORK.get());
						tabData.accept(JVPillageItems.SPIRVE_STUB.get());
						tabData.accept(JVPillageItems.SPIRVE_CHOPPER.get());
						tabData.accept(JVPillageItems.SPIRVE_MORNING_STAR.get());
						tabData.accept(JVPillageItems.SPIRVE_HAMMER.get());
						tabData.accept(JVPillageItems.SPIRVE_FLAIL.get());
						tabData.accept(JVPillageItems.SPIRVE_HORSEWHIP.get());
						tabData.accept(JVPillageItems.SPIRVE_HOOK.get());
						tabData.accept(JVPillageItems.SPIRVE_RULER.get());
						tabData.accept(JVPillageItems.SPIRVE_WOODEN_BACK_SCRATCHER.get());
						tabData.accept(JVPillageItems.SPIRVE_LADLE.get());
						tabData.accept(JVPillageItems.SPIRVE_FIRESTICK.get());
						tabData.accept(JVPillageItems.SPIRVE_SICKLE.get());
						tabData.accept(JVPillageItems.SPIRVE_WRENCH.get());
						tabData.accept(JVPillageItems.SPIRVE_LID.get());
						tabData.accept(JVPillageItems.EVIL_POTION.get());
						tabData.accept(JVPillageItems.BIG_WITCHS_HAT.get());
						tabData.accept(JVPillageItems.HAG_EYE.get());
						tabData.accept(JVPillageItems.HAGS_BRUSH.get());
						tabData.accept(JVPillageItems.PURPLE_SAND_HAG_EYE.get());
						tabData.accept(JVPillageItems.PURPLE_SAND_HAG_HAIR.get());
						tabData.accept(JVPillageItems.MUSIC_DISC_PURPLE_SAND_HAG.get());
						tabData.accept(JVPillageItems.PURPLE_SAND_ALCHEMY_BOMB.get());
						tabData.accept(JVPillageItems.PURPLE_SAND_EXPLOSIVE_ALCHEMY_BOMB.get());
						tabData.accept(JVPillageItems.PURPLE_SAND_RABBIT_SPAWN_EGG.get());
						tabData.accept(JVPillageItems.WITCH_SCHOLAR_SPAWN_EGG.get());
						tabData.accept(JVPillageItems.SPIRVE_SPAWN_EGG.get());
						tabData.accept(JVPillageItems.ROTTEN_DOG_SPAWN_EGG.get());
						tabData.accept(JVPillageItems.BIG_WITCH_SPAWN_EGG.get());
						tabData.accept(JVPillageItems.COHORT_HAG_SPAWN_EGG.get());
						tabData.accept(JVPillageItems.COVEN_HAG_ONE_SPAWN_EGG.get());
						tabData.accept(JVPillageItems.COVEN_HAG_TWO_SPAWN_EGG.get());
						tabData.accept(JVPillageItems.PURPLE_SAND_HAG_SPAWN_EGG.get());
						//海洋
						tabData.accept(JVPillageItems.GEMSTONE_GRAVEL.get());
						tabData.accept(JVPillageItems.GLITTER_SAND.get());
						tabData.accept(JVPillageItems.GLITTER_SANDSTONE.get());
						tabData.accept(JVPillageItems.GLITTER_SANDSTONE_STAIRS.get());
						tabData.accept(JVPillageItems.GLITTER_SANDSTONE_SLAB.get());
						tabData.accept(JVPillageItems.GLITTER_SANDSTONE_WALL.get());
						tabData.accept(JVPillageItems.CHISELED_GLITTER_SANDSTONE.get());
						tabData.accept(JVPillageItems.SMOOTH_GLITTER_SANDSTONE.get());
						tabData.accept(JVPillageItems.SMOOTH_GLITTER_SANDSTONE_STAIRS.get());
						tabData.accept(JVPillageItems.SMOOTH_GLITTER_SANDSTONE_SLAB.get());
						tabData.accept(JVPillageItems.CUT_GLITTER_SANDSTONE.get());
						tabData.accept(JVPillageItems.CUT_GLITTER_SANDSTONE_SLAB.get());
						tabData.accept(JVPillageItems.OCEAN_GEMSTONE_BLOCK.get());
						tabData.accept(JVPillageItems.OCEAN_GEMSTONE.get());
						tabData.accept(JVPillageItems.OCEAN_GEMSTONE_FRAGMENTS.get());
						tabData.accept(JVPillageItems.GEMSTONE_THROWING_KNIVES.get());
						tabData.accept(JVPillageItems.MALIGNASAUR_TEETH.get());
						//明草
						tabData.accept(JVPillageItems.BRIGHT_COBBLESTONE.get());
						tabData.accept(JVPillageItems.BRIGHT_COBBLESTONE_STAIRS.get());
						tabData.accept(JVPillageItems.BRIGHT_COBBLESTONE_SLAB.get());
						tabData.accept(JVPillageItems.BRIGHT_COBBLESTONE_WALL.get());
						tabData.accept(JVPillageItems.SECOND_ROUND_NIGRUM_CRATE.get());
						tabData.accept(JVPillageItems.BRIGHT_MELON_CRATE.get());
						tabData.accept(JVPillageItems.GOLDEN_BRIGHT_MELON_CRATE.get());
						tabData.accept(JVPillageItems.SECOND_ROUND_NIGRUM.get());
						tabData.accept(JVPillageItems.COOKED_SECOND_ROUND_NIGRUM.get());
						tabData.accept(JVPillageItems.SECOND_ROUND_NIGRUM_SOUP.get());
						tabData.accept(JVPillageItems.BRIGHT_MELON.get());
						tabData.accept(JVPillageItems.BRIGHT_MELON_SEEDS.get());
						tabData.accept(JVPillageItems.ROTTEN_BRIGHT_MELON.get());
						tabData.accept(JVPillageItems.GOLDEN_BRIGHT_MELON.get());
						tabData.accept(JVPillageItems.BRIGHT_GOLDEN_MELON_HAMMER.get());
						tabData.accept(JVPillageItems.HERO_SOUP.get());
						tabData.accept(JVPillageItems.THROWING_STUBBORN_STONE.get());
						tabData.accept(JVPillageItems.ANESTHETIC_THROWING_BALL.get());
						tabData.accept(JVPillageItems.GLASS_THROWING_BALL.get());
						tabData.accept(JVPillageItems.POTION_THROWING_BALL.get());
						tabData.accept(JVPillageItems.LEATHER_SLING.get());
						tabData.accept(JVPillageItems.WOODEN_SLINGSHOT.get());
						tabData.accept(JVPillageItems.BRIGHT_BOLA.get());
						//旱火
						tabData.accept(JVPillageItems.DROUGHT_FIRE_STONE.get());
						tabData.accept(JVPillageItems.DROUGHT_FIRE_BRICKS.get());
						tabData.accept(JVPillageItems.DROUGHT_FIRE_BRICK_STAIRS.get());
						tabData.accept(JVPillageItems.DROUGHT_FIRE_BRICK_SLAB.get());
						tabData.accept(JVPillageItems.DROUGHT_FIRE_BRICK_WALL.get());
						tabData.accept(JVPillageItems.DROUGHT_FIRE_MUD.get());
						tabData.accept(JVPillageItems.FIRELIGHT_STONE.get());
						//沙屿
						tabData.accept(JVPillageItems.SUN_SAND.get());
						tabData.accept(JVPillageItems.SUN_SANDSTONE.get());
						tabData.accept(JVPillageItems.SUN_SANDSTONE_STAIRS.get());
						tabData.accept(JVPillageItems.SUN_SANDSTONE_SLAB.get());
						tabData.accept(JVPillageItems.SUN_SANDSTONE_WALL.get());
						tabData.accept(JVPillageItems.CHISELED_SUN_SANDSTONE.get());
						tabData.accept(JVPillageItems.SMOOTH_SUN_SANDSTONE.get());
						tabData.accept(JVPillageItems.SMOOTH_SUN_SANDSTONE_STAIRS.get());
						tabData.accept(JVPillageItems.SMOOTH_SUN_SANDSTONE_SLAB.get());
						tabData.accept(JVPillageItems.CUT_SUN_SANDSTONE.get());
						tabData.accept(JVPillageItems.CUT_SUN_SANDSTONE_SLAB.get());
						tabData.accept(JVPillageItems.INDUSTRIAL_RESIDUAL_SOIL.get());
						tabData.accept(JVPillageItems.MEROR_PROJECTION_TABLE.get());
						tabData.accept(JVPillageItems.VIRTUAL_CAVE_CRYSTAL_ARROW.get());

					}).withSearchBar().
					withBackgroundLocation(new ResourceLocation(JVPillage.MODID, "textures/gui/container/creative_inventory/tab_item_search.png")).
					withTabsImage(new ResourceLocation(JVPillage.MODID, "textures/gui/container/creative_inventory/tabs.png")).
					build());

	public static ItemStack CarvedBanner() {
		ItemStack itemStack = new ItemStack(Items.WHITE_BANNER);
		CompoundTag compoundTag = new CompoundTag();
		ListTag listTag = new BannerPattern.Builder().addPattern(BannerPatterns.RHOMBUS_MIDDLE, DyeColor.GREEN).addPattern(BannerPatterns.STRIPE_BOTTOM, DyeColor.ORANGE).addPattern(BannerPatterns.HALF_HORIZONTAL, DyeColor.BROWN).addPattern(BannerPatterns.STRAIGHT_CROSS, DyeColor.YELLOW).addPattern(BannerPatterns.STRIPE_CENTER, DyeColor.BROWN).addPattern(BannerPatterns.BORDER, DyeColor.WHITE).addPattern(BannerPatterns.STRIPE_MIDDLE, DyeColor.BLACK).addPattern(BannerPatterns.HALF_HORIZONTAL, DyeColor.ORANGE).addPattern(BannerPatterns.BORDER, DyeColor.WHITE).addPattern(BannerPatterns.TRIANGLES_TOP, DyeColor.YELLOW).toListTag();
		compoundTag.put("Patterns", listTag);
		BlockItem.setBlockEntityData(itemStack, BlockEntityType.BANNER, compoundTag);
		itemStack.hideTooltipPart(ItemStack.TooltipPart.ADDITIONAL);
		itemStack.setHoverName(Component.translatable("block.jvpillage.carved_banner").withStyle(ChatFormatting.GOLD));
		return itemStack;
	}

}
