package com.jerotes.jerotesvillage.init;

import com.jerotes.jerotesvillage.JerotesVillage;
import net.minecraft.ChatFormatting;
import net.minecraft.core.registries.Registries;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.ListTag;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.entity.BannerPattern;
import net.minecraft.world.level.block.entity.BannerPatterns;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.RegistryObject;

public class JerotesVillageTabs {
	public static final DeferredRegister<CreativeModeTab> REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, JerotesVillage.MODID);
	//方块-物品-工具-盔甲-刷怪蛋
	public static final RegistryObject<CreativeModeTab> JEROTESVILLAGE_TAB = REGISTRY.register("jerotesvillage_tab",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.jerotesvillage.jerotesvillage_tab")).icon(() -> new ItemStack(JerotesVillageItems.JEROTESVILLAGE.get())).displayItems((parameters, tabData) -> {


						tabData.accept(JerotesVillageItems.VILLAGER_METAL_BASE_BLOCK.get());
						tabData.accept(JerotesVillageItems.VILLAGER_METAL_BLOCK.get());
						tabData.accept(JerotesVillageItems.VILLAGER_METAL_DOOR.get());
						tabData.accept(JerotesVillageItems.VILLAGER_METAL_TRAPDOOR.get());
						tabData.accept(JerotesVillageItems.VILLAGER_METAL_PRESSURE_PLATE.get());
						tabData.accept(JerotesVillageItems.CARVED_BRICKS.get());
						tabData.accept(JerotesVillageItems.CARVED_BRICK_STAIRS.get());
						tabData.accept(JerotesVillageItems.CARVED_BRICK_SLAB.get());
						tabData.accept(JerotesVillageItems.CARVED_BRICK_WALL.get());
						tabData.accept(JerotesVillageItems.CARVED_VILLAGER_CONCERTINA_WIRE.get());
						tabData.accept(JerotesVillageItems.CARVED_LODESTONE.get());
						tabData.accept(CarvedBanner());
						tabData.accept(JerotesVillageItems.SCRAP_VILLAGER_METAL.get());
						tabData.accept(JerotesVillageItems.VILLAGER_METAL_INGOT.get());
						tabData.accept(JerotesVillageItems.VILLAGER_METAL_BASE.get());
						tabData.accept(JerotesVillageItems.VILLAGER_METAL_JAVELIN.get());
						tabData.accept(JerotesVillageItems.VILLAGER_METAL_WAR_BEAST_ARMOR.get());
						tabData.accept(JerotesVillageItems.VILLAGER_METAL_GIANT_BEAST_ARMOR.get());
						tabData.accept(JerotesVillageItems.VILLAGER_METAL_SWORD.get());
						tabData.accept(JerotesVillageItems.VILLAGER_METAL_SHOVEL.get());
						tabData.accept(JerotesVillageItems.VILLAGER_METAL_PICKAXE.get());
						tabData.accept(JerotesVillageItems.VILLAGER_METAL_AXE.get());
						tabData.accept(JerotesVillageItems.VILLAGER_METAL_HOE.get());
						tabData.accept(JerotesVillageItems.VILLAGER_METAL_DAGGER.get());
						tabData.accept(JerotesVillageItems.VILLAGER_METAL_HAMMER.get());
						tabData.accept(JerotesVillageItems.VILLAGER_METAL_SPEAR.get());
						tabData.accept(JerotesVillageItems.VILLAGER_METAL_HORSEWHIP.get());
						tabData.accept(JerotesVillageItems.VILLAGER_METAL_BOW.get());
						tabData.accept(JerotesVillageItems.VILLAGER_METAL_CROSSBOW.get());
						tabData.accept(JerotesVillageItems.CARVED_VILLAGER_SPECTRAL_ARROW.get());
						tabData.accept(JerotesVillageItems.VILLAGER_METAL_SHILED.get());
						tabData.accept(JerotesVillageItems.VILLAGER_METAL_HELMET.get());
						tabData.accept(JerotesVillageItems.VILLAGER_METAL_CHESTPLATE.get());
						tabData.accept(JerotesVillageItems.VILLAGER_METAL_LEGGINGS.get());
						tabData.accept(JerotesVillageItems.VILLAGER_METAL_BOOTS.get());
						tabData.accept(JerotesVillageItems.SHRAPNEL_LAUNCHER.get());
						tabData.accept(JerotesVillageItems.ILLAGER_SIGNAL_LIGHT.get());
						tabData.accept(JerotesVillageItems.CARVED_FLAG.get());
						tabData.accept(JerotesVillageItems.CARVED_CONTACTER.get());
						tabData.accept(JerotesVillageItems.CARVED_HORN.get());
						tabData.accept(JerotesVillageItems.SPEAR_MACHINE_ITEM.get());
						tabData.accept(JerotesVillageItems.UNICYCLE_ITEM.get());
						tabData.accept(JerotesVillageItems.VILLAGER_INVITATION.get());
						tabData.accept(JerotesVillageItems.CARVED_IRON_GOLEM_CORE.get());
						tabData.accept(JerotesVillageItems.SPEAR_MACHINE_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.UNICYCLE_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.CARVED_IRON_GOLEM_SPAWN_EGG.get());
						//冒险
						tabData.accept(JerotesVillageItems.ANCIENT_CITY_MAP.get());
						tabData.accept(JerotesVillageItems.STRONGHOLD_MAP.get());
						tabData.accept(JerotesVillageItems.DESERT_PYRAMID_MAP.get());
						tabData.accept(JerotesVillageItems.JUNGLE_PYRAMID_MAP.get());
						tabData.accept(JerotesVillageItems.OCEAN_MONUMENT_MAP.get());
						tabData.accept(JerotesVillageItems.WOODLAND_MANSION_MAP.get());
						tabData.accept(JerotesVillageItems.BASTION_REMNANT_MAP.get());
						tabData.accept(JerotesVillageItems.NETHER_FORTRESS_MAP.get());
						tabData.accept(JerotesVillageItems.RUINED_PORTAL_NETHER_MAP.get());
						tabData.accept(JerotesVillageItems.END_CITY_MAP.get());
						tabData.accept(JerotesVillageItems.SECOND_ROUND_ANCHOR_CORE.get());
						//沉降
						tabData.accept(JerotesVillageItems.SEDIMENT_MUD_BRICKS.get());
						tabData.accept(JerotesVillageItems.SEDIMENT_MUD_BRICK_STAIRS.get());
						tabData.accept(JerotesVillageItems.SEDIMENT_MUD_BRICK_SLAB.get());
						tabData.accept(JerotesVillageItems.SEDIMENT_MUD_BRICK_WALL.get());
						tabData.accept(JerotesVillageItems.SEDIMENT_MOISTURE_PROOF_PASTE.get());
						tabData.accept(JerotesVillageItems.SEDIMENT_COFFIN.get());
						tabData.accept(JerotesVillageItems.SEDIMENT_URN.get());
						//灾厄
						tabData.accept(JerotesVillageItems.GLOW_SHINE.get());
						tabData.accept(JerotesVillageItems.OMINOUS_TORCH.get());
						tabData.accept(JerotesVillageItems.EXPLORER_TRACKED_ROCORD.get());
						tabData.accept(JerotesVillageItems.SECOND_ROUNDER_MAP.get());
						tabData.accept(JerotesVillageItems.ILLAGER_TOWER_MAP.get());
						tabData.accept(JerotesVillageItems.GUIDELINES_FOR_THE_CRAFT_OF_THE_SECONDER_ROUND_GEM.get());
						tabData.accept(JerotesVillageItems.SECOND_ROUNDER_GEM.get());
						tabData.accept(JerotesVillageItems.SECOND_ROUND_WORLD_TELEPORT_STONE.get());
						tabData.accept(JerotesVillageItems.OMINOUS_BANNER_RAID_TAG_DEPLOYER.get());
						tabData.accept(JerotesVillageItems.GLORY_BANNER_RAID_TAG_DEPLOYER.get());
						tabData.accept(JerotesVillageItems.EXPLORER_CAMP_MAP.get());
						tabData.accept(JerotesVillageItems.EXECUTIONERS_AXE.get());
						tabData.accept(JerotesVillageItems.EXECUTIONERS_HAMMER.get());
						tabData.accept(JerotesVillageItems.EXECUTIONERS_HALBERD.get());
						tabData.accept(JerotesVillageItems.OMINOUS_BOMB.get());
						tabData.accept(JerotesVillageItems.OMINOUS_CUTLASS.get());
						tabData.accept(JerotesVillageItems.OMINOUS_DAGGER.get());
						tabData.accept(JerotesVillageItems.OMINOUS_MACE.get());
						tabData.accept(JerotesVillageItems.OMINOUS_BOW.get());
						tabData.accept(JerotesVillageItems.OMINOUS_JAVELIN.get());
						tabData.accept(JerotesVillageItems.BITTER_COLD_SORCERY_GLOVE.get());
						tabData.accept(JerotesVillageItems.GRAVITY_COPPER_BALL.get());
						tabData.accept(JerotesVillageItems.SLAVERY_SUPERVISOR_HAMMER_WHIP.get());
						tabData.accept(JerotesVillageItems.FIREPOWER_POURER_CHAINSAW.get());
						tabData.accept(JerotesVillageItems.FIREPOWER_POURER_CROSSBOW.get());
						tabData.accept(JerotesVillageItems.CRAZY_AXE.get());
						tabData.accept(JerotesVillageItems.OMINOUS_WAR_BEAST_ARMOR.get());
						tabData.accept(JerotesVillageItems.OMINOUS_GIANT_BEAST_ARMOR.get());
						tabData.accept(JerotesVillageItems.EXPLORER_IRON_UPGRADE_SMITHING_TEMPLATE.get());
						tabData.accept(JerotesVillageItems.EXPLORER_IRON_HELMET.get());
						tabData.accept(JerotesVillageItems.EXPLORER_IRON_CHESTPLATE.get());
						tabData.accept(JerotesVillageItems.EXPLORER_IRON_LEGGINGS.get());
						tabData.accept(JerotesVillageItems.EXPLORER_IRON_BOOTS.get());
						tabData.accept(JerotesVillageItems.EXPLORER_UPGRADE_SMITHING_TEMPLATE.get());
						tabData.accept(JerotesVillageItems.EXPLORER_HELMET.get());
						tabData.accept(JerotesVillageItems.EXPLORER_CHESTPLATE.get());
						tabData.accept(JerotesVillageItems.EXPLORER_LEGGINGS.get());
						tabData.accept(JerotesVillageItems.EXPLORER_BOOTS.get());
						tabData.accept(JerotesVillageItems.HORNED_HELMET.get());
						tabData.accept(JerotesVillageItems.WARLOCK_TIARA.get());
						tabData.accept(JerotesVillageItems.WARLOCK_CASSOCK.get());
						tabData.accept(JerotesVillageItems.WARLOCK_FAKE_TIARA.get());
						tabData.accept(JerotesVillageItems.SLAVERY_SUPERVISOR_UPGRADE_SMITHING_TEMPLATE.get());
						tabData.accept(JerotesVillageItems.SLAVERY_SUPERVISOR_HELMET.get());
						tabData.accept(JerotesVillageItems.SLAVERY_SUPERVISOR_CHESTPLATE.get());
						tabData.accept(JerotesVillageItems.SLAVERY_SUPERVISOR_LEGGINGS.get());
						tabData.accept(JerotesVillageItems.SLAVERY_SUPERVISOR_BOOTS.get());
						tabData.accept(JerotesVillageItems.OMINOUS_PROBE.get());
						tabData.accept(JerotesVillageItems.OMINOUS_BANNER_PROJECTION_EMERALD_FRAGMENT.get());
						tabData.accept(JerotesVillageItems.MUSIC_DISC_OMINOUS_BANNER_PROJECTION.get());
						tabData.accept(JerotesVillageItems.BOUND_ZOMBIE_VILLAGER_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.EXPLORER_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.EXECUTIONER_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.MAPMAKER_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.DEFECTOR_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.BANNER_BEARER_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.BLASTER_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.TRUMPETER_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.TELEPORTER_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.CYCLONER_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.JAVELIN_THROWER_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.ZOMBIE_KEEPER_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.BITTER_COLD_SORCERER_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.PURPLE_SAND_WITCH_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.FIRE_SPITTER_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.WILD_FINDER_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.SUBMARINER_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.LAMP_WIZARD_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.SLAVERY_SUPERVISOR_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.FIREPOWER_POURER_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.NECROMANCY_WARLOCK_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.GAVILER_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.AX_CRAZY_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.OMINOUS_BANNER_PROJECTION_SPAWN_EGG.get());
						//苦寒
						tabData.accept(JerotesVillageItems.SNOW_FROZEN_SOIL.get());
						tabData.accept(JerotesVillageItems.ICE_ROCK.get());
						tabData.accept(JerotesVillageItems.GIANT_MONSTER_HAIR.get());
						tabData.accept(JerotesVillageItems.GIANT_MONSTER_HORN.get());
						tabData.accept(JerotesVillageItems.GIANT_MONSTER_HELMET.get());
						tabData.accept(JerotesVillageItems.GIANT_MONSTER_HORNED_HELMET.get());
						tabData.accept(JerotesVillageItems.GIANT_MONSTER_CHESTPLATE.get());
						tabData.accept(JerotesVillageItems.GIANT_MONSTER_LEGGINGS.get());
						tabData.accept(JerotesVillageItems.GIANT_MONSTER_BOOTS.get());
						tabData.accept(JerotesVillageItems.ICE_ROCK_THROWING_BALL.get());
						tabData.accept(JerotesVillageItems.WILDERNESS_WOLF_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.GIANT_MONSTER_SPAWN_EGG.get());
						//紫沙
						tabData.accept(JerotesVillageItems.PURPLE_SAND.get());
						tabData.accept(JerotesVillageItems.PURPLE_SANDSTONE.get());
						tabData.accept(JerotesVillageItems.PURPLE_SANDSTONE_STAIRS.get());
						tabData.accept(JerotesVillageItems.PURPLE_SANDSTONE_SLAB.get());
						tabData.accept(JerotesVillageItems.PURPLE_SANDSTONE_WALL.get());
						tabData.accept(JerotesVillageItems.CHISELED_PURPLE_SANDSTONE.get());
						tabData.accept(JerotesVillageItems.SMOOTH_PURPLE_SANDSTONE.get());
						tabData.accept(JerotesVillageItems.SMOOTH_PURPLE_SANDSTONE_STAIRS.get());
						tabData.accept(JerotesVillageItems.SMOOTH_PURPLE_SANDSTONE_SLAB.get());
						tabData.accept(JerotesVillageItems.CUT_PURPLE_SANDSTONE.get());
						tabData.accept(JerotesVillageItems.CUT_PURPLE_SANDSTONE_SLAB.get());
						tabData.accept(JerotesVillageItems.ENCHANTED_STONE.get());
						tabData.accept(JerotesVillageItems.SPIRVE_HEAD.get());
						tabData.accept(JerotesVillageItems.HAGS_CAULDRON.get());
						tabData.accept(JerotesVillageItems.UNSTABLE_HAGS_CAULDRON.get());
						tabData.accept(JerotesVillageItems.DIRTY_HAGS_CAULDRON.get());
						tabData.accept(JerotesVillageItems.NEW_HAGS_CAULDRON.get());
						tabData.accept(JerotesVillageItems.BLAMER_SOUL.get());
						tabData.accept(JerotesVillageItems.BLAMER_ROBE.get());
						tabData.accept(JerotesVillageItems.PURPLE_SANDWICH.get());
						tabData.accept(JerotesVillageItems.WITCH_COVEN_MAP.get());
						tabData.accept(JerotesVillageItems.WITCH_RESIDENCE_MAP.get());
						tabData.accept(JerotesVillageItems.SPIRVE_HELMET.get());
						tabData.accept(JerotesVillageItems.SPIRVE_CHESTPLATE.get());
						tabData.accept(JerotesVillageItems.SPIRVE_LEGGINGS.get());
						tabData.accept(JerotesVillageItems.SPIRVE_BOOTS.get());
						tabData.accept(JerotesVillageItems.SPIRVE_BROOM.get());
						tabData.accept(JerotesVillageItems.SPIRVE_DUSTPAN.get());
						tabData.accept(JerotesVillageItems.SPIRVE_INSECT_NET.get());
						tabData.accept(JerotesVillageItems.SPIRVE_MOP.get());
						tabData.accept(JerotesVillageItems.SPIRVE_KITCHEN_KNIFE.get());
						tabData.accept(JerotesVillageItems.SPIRVE_SPATULA.get());
						tabData.accept(JerotesVillageItems.SPIRVE_PAN.get());
						tabData.accept(JerotesVillageItems.SPIRVE_GOURD_LADLE.get());
						tabData.accept(JerotesVillageItems.SPIRVE_SAW.get());
						tabData.accept(JerotesVillageItems.SPIRVE_FRAME_SAW.get());
						tabData.accept(JerotesVillageItems.SPIRVE_PINCER.get());
						tabData.accept(JerotesVillageItems.SPIRVE_SISSORS.get());
						tabData.accept(JerotesVillageItems.SPIRVE_RAZOR.get());
						tabData.accept(JerotesVillageItems.SPIRVE_DUSTER.get());
						tabData.accept(JerotesVillageItems.SPIRVE_BROKEN_BOOTLE.get());
						tabData.accept(JerotesVillageItems.SPIRVE_FORK.get());
						tabData.accept(JerotesVillageItems.SPIRVE_STUB.get());
						tabData.accept(JerotesVillageItems.SPIRVE_CHOPPER.get());
						tabData.accept(JerotesVillageItems.SPIRVE_MORNING_STAR.get());
						tabData.accept(JerotesVillageItems.SPIRVE_HAMMER.get());
						tabData.accept(JerotesVillageItems.SPIRVE_FLAIL.get());
						tabData.accept(JerotesVillageItems.SPIRVE_HORSEWHIP.get());
						tabData.accept(JerotesVillageItems.SPIRVE_HOOK.get());
						tabData.accept(JerotesVillageItems.SPIRVE_RULER.get());
						tabData.accept(JerotesVillageItems.SPIRVE_WOODEN_BACK_SCRATCHER.get());
						tabData.accept(JerotesVillageItems.SPIRVE_LADLE.get());
						tabData.accept(JerotesVillageItems.SPIRVE_FIRESTICK.get());
						tabData.accept(JerotesVillageItems.SPIRVE_SICKLE.get());
						tabData.accept(JerotesVillageItems.SPIRVE_WRENCH.get());
						tabData.accept(JerotesVillageItems.SPIRVE_LID.get());
						tabData.accept(JerotesVillageItems.EVIL_POTION.get());
						tabData.accept(JerotesVillageItems.BIG_WITCHS_HAT.get());
						tabData.accept(JerotesVillageItems.HAG_EYE.get());
						tabData.accept(JerotesVillageItems.HAGS_BRUSH.get());
						tabData.accept(JerotesVillageItems.PURPLE_SAND_HAG_EYE.get());
						tabData.accept(JerotesVillageItems.PURPLE_SAND_HAG_HAIR.get());
						tabData.accept(JerotesVillageItems.MUSIC_DISC_PURPLE_SAND_HAG.get());
						tabData.accept(JerotesVillageItems.PURPLE_SAND_ALCHEMY_BOMB.get());
						tabData.accept(JerotesVillageItems.PURPLE_SAND_EXPLOSIVE_ALCHEMY_BOMB.get());
						tabData.accept(JerotesVillageItems.PURPLE_SAND_RABBIT_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.WITCH_SCHOLAR_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.SPIRVE_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.BLAMER_NECROMANCY_WARLOCK_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.FURY_BLAMER_NECROMANCY_WARLOCK_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.ROTTEN_DOG_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.BIG_WITCH_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.COHORT_HAG_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.COVEN_HAG_ONE_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.COVEN_HAG_TWO_SPAWN_EGG.get());
						tabData.accept(JerotesVillageItems.PURPLE_SAND_HAG_SPAWN_EGG.get());
						//海洋
						tabData.accept(JerotesVillageItems.GEMSTONE_GRAVEL.get());
						tabData.accept(JerotesVillageItems.GLITTER_SAND.get());
						tabData.accept(JerotesVillageItems.GLITTER_SANDSTONE.get());
						tabData.accept(JerotesVillageItems.GLITTER_SANDSTONE_STAIRS.get());
						tabData.accept(JerotesVillageItems.GLITTER_SANDSTONE_SLAB.get());
						tabData.accept(JerotesVillageItems.GLITTER_SANDSTONE_WALL.get());
						tabData.accept(JerotesVillageItems.CHISELED_GLITTER_SANDSTONE.get());
						tabData.accept(JerotesVillageItems.SMOOTH_GLITTER_SANDSTONE.get());
						tabData.accept(JerotesVillageItems.SMOOTH_GLITTER_SANDSTONE_STAIRS.get());
						tabData.accept(JerotesVillageItems.SMOOTH_GLITTER_SANDSTONE_SLAB.get());
						tabData.accept(JerotesVillageItems.CUT_GLITTER_SANDSTONE.get());
						tabData.accept(JerotesVillageItems.CUT_GLITTER_SANDSTONE_SLAB.get());
						tabData.accept(JerotesVillageItems.OCEAN_GEMSTONE_BLOCK.get());
						tabData.accept(JerotesVillageItems.OCEAN_GEMSTONE.get());
						tabData.accept(JerotesVillageItems.OCEAN_GEMSTONE_FRAGMENTS.get());
						tabData.accept(JerotesVillageItems.GEMSTONE_THROWING_KNIVES.get());
						tabData.accept(JerotesVillageItems.MALIGNASAUR_TEETH.get());
						//明草
						tabData.accept(JerotesVillageItems.BRIGHT_COBBLESTONE.get());
						tabData.accept(JerotesVillageItems.BRIGHT_COBBLESTONE_STAIRS.get());
						tabData.accept(JerotesVillageItems.BRIGHT_COBBLESTONE_SLAB.get());
						tabData.accept(JerotesVillageItems.BRIGHT_COBBLESTONE_WALL.get());
						tabData.accept(JerotesVillageItems.SECOND_ROUND_NIGRUM_CRATE.get());
						tabData.accept(JerotesVillageItems.BRIGHT_MELON_CRATE.get());
						tabData.accept(JerotesVillageItems.GOLDEN_BRIGHT_MELON_CRATE.get());
						tabData.accept(JerotesVillageItems.SECOND_ROUND_NIGRUM.get());
						tabData.accept(JerotesVillageItems.COOKED_SECOND_ROUND_NIGRUM.get());
						tabData.accept(JerotesVillageItems.SECOND_ROUND_NIGRUM_SOUP.get());
						tabData.accept(JerotesVillageItems.BRIGHT_MELON.get());
						tabData.accept(JerotesVillageItems.BRIGHT_MELON_SEEDS.get());
						tabData.accept(JerotesVillageItems.ROTTEN_BRIGHT_MELON.get());
						tabData.accept(JerotesVillageItems.GOLDEN_BRIGHT_MELON.get());
						tabData.accept(JerotesVillageItems.BRIGHT_GOLDEN_MELON_HAMMER.get());
						tabData.accept(JerotesVillageItems.HERO_SOUP.get());
						tabData.accept(JerotesVillageItems.THROWING_STUBBORN_STONE.get());
						tabData.accept(JerotesVillageItems.ANESTHETIC_THROWING_BALL.get());
						tabData.accept(JerotesVillageItems.VILLAGER_METAL_THROWING_BALL.get());
						tabData.accept(JerotesVillageItems.GLASS_THROWING_BALL.get());
						tabData.accept(JerotesVillageItems.POTION_THROWING_BALL.get());
						tabData.accept(JerotesVillageItems.LEATHER_SLING.get());
						tabData.accept(JerotesVillageItems.WOODEN_SLINGSHOT.get());
						tabData.accept(JerotesVillageItems.BRIGHT_BOLA.get());
						//旱火
						tabData.accept(JerotesVillageItems.DROUGHT_FIRE_STONE.get());
						tabData.accept(JerotesVillageItems.DROUGHT_FIRE_BRICKS.get());
						tabData.accept(JerotesVillageItems.DROUGHT_FIRE_BRICK_STAIRS.get());
						tabData.accept(JerotesVillageItems.DROUGHT_FIRE_BRICK_SLAB.get());
						tabData.accept(JerotesVillageItems.DROUGHT_FIRE_BRICK_WALL.get());
						tabData.accept(JerotesVillageItems.DROUGHT_FIRE_MUD.get());
						tabData.accept(JerotesVillageItems.FIRELIGHT_STONE.get());
						//沙屿
						tabData.accept(JerotesVillageItems.SUN_SAND.get());
						tabData.accept(JerotesVillageItems.SUN_SANDSTONE.get());
						tabData.accept(JerotesVillageItems.SUN_SANDSTONE_STAIRS.get());
						tabData.accept(JerotesVillageItems.SUN_SANDSTONE_SLAB.get());
						tabData.accept(JerotesVillageItems.SUN_SANDSTONE_WALL.get());
						tabData.accept(JerotesVillageItems.CHISELED_SUN_SANDSTONE.get());
						tabData.accept(JerotesVillageItems.SMOOTH_SUN_SANDSTONE.get());
						tabData.accept(JerotesVillageItems.SMOOTH_SUN_SANDSTONE_STAIRS.get());
						tabData.accept(JerotesVillageItems.SMOOTH_SUN_SANDSTONE_SLAB.get());
						tabData.accept(JerotesVillageItems.CUT_SUN_SANDSTONE.get());
						tabData.accept(JerotesVillageItems.CUT_SUN_SANDSTONE_SLAB.get());
						tabData.accept(JerotesVillageItems.INDUSTRIAL_RESIDUAL_SOIL.get());
						tabData.accept(JerotesVillageItems.MEROR_PROJECTION_TABLE.get());
						tabData.accept(JerotesVillageItems.VIRTUAL_CAVE_CRYSTAL_ARROW.get());

					}).withSearchBar().
					withBackgroundLocation(new ResourceLocation(JerotesVillage.MODID, "textures/gui/container/creative_inventory/tab_item_search.png")).
					withTabsImage(new ResourceLocation(JerotesVillage.MODID, "textures/gui/container/creative_inventory/tabs.png")).
					build());

	public static ItemStack CarvedBanner() {
		ItemStack itemStack = new ItemStack(Items.WHITE_BANNER);
		CompoundTag compoundTag = new CompoundTag();
		ListTag listTag = new BannerPattern.Builder().addPattern(BannerPatterns.RHOMBUS_MIDDLE, DyeColor.GREEN).addPattern(BannerPatterns.STRIPE_BOTTOM, DyeColor.ORANGE).addPattern(BannerPatterns.HALF_HORIZONTAL, DyeColor.BROWN).addPattern(BannerPatterns.STRAIGHT_CROSS, DyeColor.YELLOW).addPattern(BannerPatterns.STRIPE_CENTER, DyeColor.BROWN).addPattern(BannerPatterns.BORDER, DyeColor.WHITE).addPattern(BannerPatterns.STRIPE_MIDDLE, DyeColor.BLACK).addPattern(BannerPatterns.HALF_HORIZONTAL, DyeColor.ORANGE).addPattern(BannerPatterns.BORDER, DyeColor.WHITE).addPattern(BannerPatterns.TRIANGLES_TOP, DyeColor.YELLOW).toListTag();
		compoundTag.put("Patterns", listTag);
		BlockItem.setBlockEntityData(itemStack, BlockEntityType.BANNER, compoundTag);
		itemStack.hideTooltipPart(ItemStack.TooltipPart.ADDITIONAL);
		itemStack.setHoverName(Component.translatable("block.jerotesvillage.carved_banner").withStyle(ChatFormatting.GOLD));
		return itemStack;
	}

}
